### ISSUE TITLE
디렉토리 구조 변경 필요

### ISSUE THREAD

**Issue by chanhee-park** [hm00081/sooyeonjang#2]
첫 진입점이 `./public/index.html`이고, js와 css코드는 `./scr/...`에 있네요.  
json 파일이 위치한 곳도 약간 이상하구요. 
구조를 아래와 같이 변경할 필요가 있어보여요.

- scr
  - [js files]
- style
  - [css files]
- data
  - [json files]
 
index.html
README.md
package.json
.gitignore
... etc

**Comment by hm00081** [comment]
안녕하세요 찬희님, 우선 적어주신대로 수정을 해봤습니다.

현재 해야 할 가장 큰 작업은 각 사이클의 유사도에 맞는 채도 조절 작업입니다.
[수연장 채도.pdf](https://github.com/hm00081/sooyeonjang/files/6477672/default.pdf)

그 외에 자잘한 변경 작업은 우선 제가 해보고 있습니다. 

시간이 괜찮으시면 다음주 랩미팅 이전에 줌으로 미팅을 한번 진행했으면 좋겠는데 시간 괜찮으실까요?

감사합니다.

**Comment by chanhee-park** [comment]
이슈는 하나의 스레드에서 댓글로 모든 작업을 더해가기보다는 작업별로 개별 이슈 스레드를 가지도록 하는게 관리하기 좋을 것 같습니다. 

채도 변경 작업이 필요하시다기에 채도 변경 작업에 대한 이슈를 달아놨습니다. 

관련 얘기는 이슈 내 댓글 기능으로 논의하시죠~
급하게 정해야할 항목이 있으면 메일이나 카톡주세요.

감사합니다. 
박찬희 드림


> 2021. 5. 14. 오후 5:53, Kwanghyuk Moon ***@***.***> 작성:
> 
>  사이클의 유사도에 맞는 채도
