### ISSUE TITLE
채도 변경 작업 

### ISSUE THREAD

**Issue by chanhee-park** [hm00081/sooyeonjang#3]
사이클의 유사도에 맞게 채도를 조절해야함

미팅 필요

**Comment by chanhee-park** [comment]
@hm00081 월요일 오후에 미팅 괜찮으세요? 저는 월요일 두시에서 다섯시 사이에 시간이 납니다.

**Comment by hm00081** [comment]
전 다 괜찮아서 편하신 시간에 진행하시면 될 것 같습니다.

**Comment by chanhee-park** [comment]
네 그럼 두시에 뵙는걸로 하시죠~ 다른 분도 필요하다면 자유롭게 초대해주세요^^
